### ISSUE TITLE
Add patientMatcher to the list of the available ga4gh MME software

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#131]
Here: https://github.com/ga4gh/mme-apis/wiki/Implementations

**Comment by northwestwitch** [comment]
https://github.com/ga4gh/mme-apis/issues/160

**Comment by Relequestual** [comment]
Think we still need to wait till you've connected to two or more nodes.
I think the group would also hope you can make it to one of our conference calls.
Apologies if I'm wrong, but I don't remember hearing from you on a call.

**Comment by northwestwitch** [comment]
It's OK, we are going to be connected to MatchBox this week or the next so we'll be compliant. I did an intervention on the December call and before that one of our collaborator introduced our node during the ASHG  in person meeting in October (I wasn't attending), but if you want I could introduce our software during one of the next calls!

**Comment by northwestwitch** [comment]
Hi again! We're connected to 2 other services since some time (MyGene2 and MatchBox), so perhaps we could be added to the list of implementations now? 
Thanks, Chiara

**Comment by Relequestual** [comment]
Hi Chiara,
Danielle (@dazzariti) should be able to do this for you.
What content do you want there?

I've just returned to work so have a lot of catcching up to do!

**Comment by northwestwitch** [comment]
Thanks @Relequestual and @dazzariti!

What about this:

PatientMatcher: https://github.com/Clinical-Genomics/patientMatcher. Developed and used in production by Clinical Genomics, SciLifeLab Stockholm. A Python web application using Flask framework and MongoDB that implements the MME API and allows to customize the patient matching algorithm.

**Comment by dazzariti** [comment]
Thanks @northwestwitch - I've added to the implementations page.

**Comment by northwestwitch** [comment]
Thank you @dazzariti & @Relequestual !
