### ISSUE TITLE
Add this repo to Sonarcloud

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#307]
@henrikstranneheim when you have time? Thanks!

**Comment by henrikstranneheim** [comment]
<img width="1402" alt="Screenshot 2022-08-23 at 11 06 06" src="https://user-images.githubusercontent.com/584738/186118746-b33ceed1-055a-4d52-a347-c24d7528aa50.png">
Fixed 😄

**Comment by northwestwitch** [comment]
Could have been worse: :grin:

<img width="971" alt="image" src="https://user-images.githubusercontent.com/28093618/186119981-b6bf1b58-8680-44ea-8eb2-d4e34dd57ad1.png">

**Comment by henrikstranneheim** [comment]
Looks quite decent I think 👍
