### ISSUE TITLE
Endpoints that should be reachable thru a firewall and endpoints to be used from within the server

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/patientMatcher#77]
Endpoints that should be **reachable by external requests** are:

1. server_url/metrics (GET method)

1. server_url/heartbeat (GET method)

1. server_url/match (POST method) *

Endpoints that should be reached **from within the same server**:

1. server_url/patient/add (POST method)

1. server_url/patient/delete/<patient_id> (DELETE method)

1. server_url/nodes (GET method)

1. server_url/match (POST method) *

1. server_url/match/external/<patient_id> (POST method)

1. server_url/matches (GET method)

* == endpoint which can be reached from the same server or by external request

**Comment by ingkebil** [comment]
Endpoints that should be reached from within the same server: these should work out of the box. There is no restriction there.

Endpoints that should be reachable by external requests are now set up. I have no way of testing this tho.

**Comment by northwestwitch** [comment]
Testing the metrics endpoint which should be reached from the outside: 

- Test from a terminal within **clinical-db** :
```
curl -X GET   -H 'X-Auth-Token: ************' localhost:8095/metrics
```
************ = token.

result:
"metrics": {
    "dateGenerated": "2019-07-02", 
    "numberOfCases": 1, 
    "numberOfCasesWithDiagnosis": 0, 
    "numberOfFeatures": 0, 
    "numberOfGenes": 3, 
    "numberOfPotentialMatchesSent": 0, 
    "numberOfRequestsReceived": 0, 
    "numberOfSubmitters": 1, 
    "numberOfUniqueFeatures": 0, 
    "numberOfUniqueGenes": 3, 
    "numberOfUniqueGenesMatched": 0, 
    "numberOfUniqueVariants": 1, 
    "numberOfVariants": 3
  }
}

- Testing the same from outside the server:
```
curl -X GET   -H 'X-Auth-Token: ************'   patientmatcher.scilifelab.se:8095/metrics
```
I get operation timed out error :(

@ingkebil are domain and port correct?

**Comment by ingkebil** [comment]
you shouldn't add the port when testing outside of clinical-db

**Comment by northwestwitch** [comment]
Ok after that fix, removing the port and adding https, I can confirm that the following endpoints work in production server. 👍 

- metrics
![image](https://user-images.githubusercontent.com/28093618/60511576-9944d100-9cd2-11e9-856c-b5ca2c736bb1.png)


- heartbeat
![image](https://user-images.githubusercontent.com/28093618/60511597-a6fa5680-9cd2-11e9-90b0-36a0db88243c.png)


- match
![image](https://user-images.githubusercontent.com/28093618/60511781-14a68280-9cd3-11e9-9ff0-fd8d9fb8f998.png)

**Comment by ingkebil** [comment]
alright! :nail_care:

**Comment by ingkebil** [comment]
Can you try again?

**Comment by northwestwitch** [comment]
It woks, thanks!!! 🎉🍾
